library(Seurat)
library(Seurat)
library(gridExtra)
library(dplyr)
library(patchwork)
library(VGAM)
library(gplots)
library(ggplot2)
library(pracma)
library(resample)
library(foreach)
library(distances)
library(utils)
library(devtools)
devtools::install_github("JSB-UCLA/scDEED")
Sys.setenv(INCLUDE = "/software/geos/3.8.1/include:/software/gcc/8.4.0/include")
old_path <- Sys.getenv("PATH")
Sys.setenv(PATH = paste("/software/geos/3.8.1/bin", old_path, sep = ":"))
install.packages("BiocManager", repos="https://cloud.r-project.org/")
install.packages("Rcpp", repos="https://cloud.r-project.org/")
install.packages("png", repos="https://cloud.r-project.org/")
BiocManager::install("multtest")
install.packages("Rfast", repos="https://cloud.r-project.org/")
